apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ include "int-email.fullname" . }}-tls-cert"
  namespace: "{{ .Release.Namespace }}"
spec:
  {{- range .Values.ingress.tls }}
  secretName: "{{ .secretName }}"
  {{- end }}
  issuerRef:
    name: "{{ .Values.tls.cert.issuer.name }}-int-email"
    kind: Issuer
  dnsNames:
    {{- range .Values.ingress.hosts }}
    - "{{ .host }}"
    {{- end }}
  usages:
    - "server auth"
    - "digital signature"
    - "key encipherment"
