{{- $fullName := include "int-email.fullname" . -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "{{ .Values.tls.cert.issuer.name }}-int-email"
  namespace: "{{ .Release.Namespace }}"
spec:
  acme:
    server: {{ .Values.tls.cert.acme.server }}
    email: {{ .Values.tls.cert.acme.email }}
    privateKeySecretRef:
      name: {{ .Values.tls.cert.issuer.name }}
    solvers:
      - dns01:
          cloudDNS: # Example for Google Cloud DNS, use your appropriate provider
            project: "{{ .Values.cloud.project }}"
            serviceAccountSecretRef:
              name: gcp-dns-secret
              key: key.json
