api:
  event:
    type: "com_awakari_email_v1"
  interests:
    detailsUriPrefix: "https://awakari.com/sub-details.html?id="
  writer:
    uri: "api:50051"

# prod
cert:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
  issuer:
    name: letsencrypt

ingress:
  hosts:
    - host: email.awakari.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: int-email-tls-server
      hosts:
        - email.awakari.com
